#ifndef __BUFFERED_UART_REGS_H__
#define __BUFFERED_UART_REGS_H__

#include <io.h>

/* STATUS register */
#define BUFFERED_UART_STATUS_REG    0
#define IOADDR_BUFFERED_UART_STATUS(base) \
    __IO_CALC_ADDRESS_NATIVE(base, BUFFERED_UART_STATUS_REG)
#define IORD_BUFFERED_UART_STATUS(base) \
    IORD(base, BUFFERED_UART_STATUS_REG)
#define IOWR_BUFFERED_UART_STATUS(base, data) \
    IOWR(base, BUFFERED_UART_STATUS_REG, data)

#define BUFFERED_UART_STATUS_RXE_MSK        (0x8000)
#define BUFFERED_UART_STATUS_RXE_OFST       (15)
#define BUFFERED_UART_STATUS_RXNE_MSK       (0x4000)
#define BUFFERED_UART_STATUS_RXNE_OFST      (14)
#define BUFFERED_UART_STATUS_RXF_MSK        (0x2000)
#define BUFFERED_UART_STATUS_RXF_OFST       (13)
#define BUFFERED_UART_STATUS_RXHF_MSK       (0x1000)
#define BUFFERED_UART_STATUS_RXHF_OFST      (12)
#define BUFFERED_UART_STATUS_TXF_MSK        (0x0800)
#define BUFFERED_UART_STATUS_TXF_OFST       (11)
#define BUFFERED_UART_STATUS_TXNF_MSK       (0x0400)
#define BUFFERED_UART_STATUS_TXNF_OFST      (10)
#define BUFFERED_UART_STATUS_TXE_MSK        (0x0200)
#define BUFFERED_UART_STATUS_TXE_OFST       (9)
#define BUFFERED_UART_STATUS_TXHE_MSK       (0x0100)
#define BUFFERED_UART_STATUS_TXHE_OFST      (8)
#define BUFFERED_UART_STATUS_ROVF_MSK       (0x0080)
#define BUFFERED_UART_STATUS_ROVF_OFST      (7)

#define BUFFERED_UART_STATUS_CAUSES_MSK     (0x7780)

/* INTR register */
#define BUFFERED_UART_INTR_REG      1
#define IOADDR_BUFFERED_UART_INTR(base) \
    __IO_CALC_ADDRESS_NATIVE(base, BUFFERED_UART_INTR_REG)
#define IORD_BUFFERED_UART_INTR(base) \
    IORD(base, BUFFERED_UART_INTR_REG)
#define IOWR_BUFFERED_UART_INTR(base, data) \
    IOWR(base, BUFFERED_UART_INTR_REG, data)

#define BUFFERED_UART_INTR_RXNE_MSK         (0x4000)
#define BUFFERED_UART_INTR_RXNE_OFST        (14)
#define BUFFERED_UART_INTR_RXF_MSK          (0x2000)
#define BUFFERED_UART_INTR_RXF_OFST         (13)
#define BUFFERED_UART_INTR_RXHF_MSK         (0x1000)
#define BUFFERED_UART_INTR_RXHF_OFST        (12)
#define BUFFERED_UART_INTR_TXNF_MSK         (0x0400)
#define BUFFERED_UART_INTR_TXNF_OFST        (10)
#define BUFFERED_UART_INTR_TXE_MSK          (0x0200)
#define BUFFERED_UART_INTR_TXE_OFST         (9)
#define BUFFERED_UART_INTR_TXHE_MSK         (0x0100)
#define BUFFERED_UART_INTR_TXHE_OFST        (8)
#define BUFFERED_UART_INTR_ROVF_MSK         (0x0080)
#define BUFFERED_UART_INTR_ROVF_OFST        (7)

#define BUFFERED_UART_INTR_IRQE_MSK         (0x0001)
#define BUFFERED_UART_INTR_IRQE_OFST        (0)

/* DATA register */
#define BUFFERED_UART_DATA_REG      2
#define IOADDR_BUFFERED_UART_DATA(base) \
    __IO_CALC_ADDRESS_NATIVE(base, BUFFERED_UART_DATA_REG)
#define IORD_BUFFERED_UART_DATA(base) \
    IORD(base, BUFFERED_UART_DATA_REG)
#define IOWR_BUFFERED_UART_DATA(base, data) \
    IOWR(base, BUFFERED_UART_DATA_REG, data)

#define BUFFERED_UART_DATA_RXE_MSK          (0x8000)
#define BUFFERED_UART_DATA_RXE_OFST         (15)
#define BUFFERED_UART_DATA_RXDATA_MSK       (0x01ff)
#define BUFFERED_UART_DATA_RXDATA_OFST      (0)
#define BUFFERED_UART_DATA_TXDATA_MSK       (0x01ff)
#define BUFFERED_UART_DATA_TXDATA_OFST      (0)

/* DIVIDER register */
#define BUFFERED_UART_DIVIDER_REG   3
#define IOADDR_BUFFERED_UART_DIVIDER(base) \
    __IO_CALC_ADDRESS_NATIVE(base, BUFFERED_UART_DIVIDER_REG)
#define IORD_BUFFERED_UART_DIVIDER(base) \
    IORD(base, BUFFERED_UART_DIVIDER_REG)
#define IOWR_BUFFERED_UART_DIVIDER(base, data) \
    IOWR(base, BUFFERED_UART_DIVIDER_REG, data)

#endif /* __BUFFERED_UART_REGS_H__ */
